src/cqe.rs
tests/write.rs

A lifetime bug with the buffers passed to the SQE: the intermediate iovec did not live until the SQE was submitted.

Fix bug that was showing up in tests/write.rs

---

src/registrar.rs

Previously, they were not inverting the error code.

Make Registrar's methods use resultify

---

src/lib.rs

Hi :wave:,
Thanks for writing this repo and also for all your awesome work on async/await!
I stumbled across segmentation fault and think this PR should fix it.  I'm much less familiar with Rust than C so apologies if the fix is incorrect.
Either way, I created a demonstration repo so it should be very easy to at least replicate the segfault.
You can find [the repo here](https://github.com/michael-grunder/iou-example-project).
Cheers!
Mike

Possible SIGSEGV fix for IoUring::peek_for_cqe

---

src/sqe.rs

The flag should be set for pre-registered fds, not pre-registered buffers.

Remove incorrect flag setting from fixed IO prep.

---

src/lib.rs

Here are some docs for `SetupFlags`. Can I ask for advice on wording for `SQ_AFF`? 
`SQPOLL` creates a kernel thread to poll the submission queue and `SQ_AFF` has something to do with that thread, but I don't entirely understand what. My best understanding is there's some thread in userland resposible for the `SubmissionQueue`, and `SQ_AFF` forces the kernel thread to be spawned by the CPU of the userland thread.

Added documentation for SetupFlags

---

Cargo.toml
src/cqe.rs
src/sqe.rs

The only change to the public API is to make `prep_timeout` align with liburing's `io_uring_prep_timeout`, including support for flags.
In a future PR, I'd like to add all of the other prep functions from liburing as well.
cc @mxxo Would you like to review and give feedback?

Use functions from liburing as much as possible.

---

Cargo.toml
src/cqe.rs
src/lib.rs
src/registrar.rs
src/sqe.rs

This is a legacy of a time in the development history when uring-sys was
*actually* just a submodule of iou. But its its own crate with its own
identity, API, versioning plan, etc, and we shouldn't re-expor the
entire thing.

Stop re-exporting uring-sys.

---

src/cqe.rs
src/sqe.rs

Add some doc tests for some of the simpler queue API functions. 
On my machine, the `is_timeout` test fails for now (#15), and if you like I can make it `no_run`.  
As is, maybe it's useful as an indicator that timeouts aren't supported? 
Thank you :smile:

Flesh out queue documentation

---

src/sqe.rs

In SubmissionQueue::submit_and_wait_with_timeout, we failed to set
the user_data of the timeout we prep to LIBURING_UDATA_TIMEOUT.

Fix SQ timeout user_data bug

---

Cargo.toml
src/lib.rs
src/sqe.rs
tests/accept.rs
tests/connect.rs
tests/poll.rs
tests/socket.rs

@withoutboats need your opinion about my tryout with nix types

Prep methods  for additional io_uring features

---

src/cqe.rs
src/lib.rs

Rather than passing around a reference into the CQE buffer, just copy
the (small) data of a CQE out of it. This will simplify implementing
better CQE processing APIs also.
Credit where its due: this idea originated with quininer's
implementation of io-uring.

Simplify CQEs by making them fully owned.

---

src/sqe.rs

An offset is a file position, so it can be bigger than usize in
32-bit platforms.

sqe: change offset to u64

---

Cargo.toml
src/lib.rs
src/sqe.rs

This patch implements a couple of more prep operations, for the
following opcodes:
- IORING_OP_FALLOCATE,
- IORING_OP_OPENAT,
- IORING_OP_READ,
- IORING_OP_WRITE,
- IORING_OP_STATX
I did my best to strike a good balance between using friendly data
structures, especially for flags, and raw libc types. In particular:
* for open, the "flags" field is kept as a libc::c_int, because that
is the way that OpenFlagsExt uses to pass custom flags, but mode
is made into a bitflag. A CString is used to hold the path name
because we need something that can hold storage and play well with
ffi.
* for statx, flags are a bitflag but the buffer is written to a
structure defined by the libc crate.
Those changes may require an update of the uring-sys crate. Locally,
I tested them with …

implement more prep operations

---

src/lib.rs
src/registrar.rs
src/sqe.rs
tests/fileset-placeholder.rs
tests/fixed-file-write.rs

This PR reduces end user complexity for properly setting up fixed file IO in the kernel. 
The fixed file interface was a little confusing for me (as opposed to fixed buffers, an entirely different thing as I just learned). After registering your `RawFd`'s, you had to pass the index of that fd as registered in the kernel fileset (not the fd itself) into prep methods. Then, you had to set `SubmissionFlags::FIXED_FILE` after the prep call. 
This PR introduces a new type representing a member of the kernel fileset called `RegisteredFd`. After a successful call to `Registrar::register_files(&fds)`, you can access the currently registered files using a new `Registrar` member function `fileset()`. This returns a slice of registered file references owned by the registrar.  The only way to get …

Add explicit registered file type

---

src/completion_queue.rs
src/cqe.rs
src/lib.rs
src/registrar.rs
src/sqe.rs
src/submission_queue.rs
tests/cqes-iter.rs
tests/fileset-placeholder.rs
tests/fixed-file-write.rs

Now they only have one lifetime and there are methods to get them from
IoUring directly. Also added tests for them and fixed imports in other
tests.

Improve CQE iters

---

src/sqe.rs

These use a `*mut libc::msghdr` unfortunately; users are responsible for
constructing that themselves.

Add prep_sendmsg and prep_recvmsg

---

src/cqe.rs
src/lib.rs
src/registrar/mod.rs
src/registrar/registered.rs
src/sqe.rs
tests/read.rs
tests/register-buffers.rs
tests/write.rs

cc @mxxo 
Generalizes `RegisteredFd` to also support `RegisteredBuf` with a similar strategy. Now, users can pre-register both FDs and buffers and pass either to `prep_read` and `prep_write` to get a correctly prepared IO event.

Add RegisteredBuf API to manage registered buffers

---

src/cqe.rs

Makes `CQE` implement `std::fmt::Debug`. At the moment it's simply a #[derive(Debug)], but the existence of the
impl is more important than how it's printed, at least initially.

Implement Debug for CQE

---

src/completion_queue.rs
src/cqe.rs
src/submission_queue.rs

I did a clippy run and it suggested switching to `ptr.is_null()` which lets us avoid the possible temporary pointer.

use is_null method for pointer checks (clippy lint)

---

src/sqe.rs

This structure is likely to be embedded in other structure so it
has a stable address. Having a debug implementation helps so that
the users can simply #[derive(Debug)]

add a debug implementation for SockAddrStorage

---

src/sqe.rs

This patch fixes a bug in `SQE::prep_recv` where `uring_sys::io_uring_prep_send` was being called instead of the corresponding `recv` function.

Fix uring_sys call in SQE recv prep helper
